### ISSUE TITLE
com.reactlibrary.BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by kdfemi** [GetMetaMap/metamap-reactnative-plugin#68]
Using com.reactlibrary conflicts with other packages using same name

**Comment by AvoSukiasyan** [comment]
Hi @kdfemi. I'll check it and get back to you.

**Comment by crislizame** [comment]
i have the same problem :(

**Comment by AvoSukiasyan** [comment]
I guess it the related to some conflict with other libraries. I changed some names and published a new version. the last version is 4.3.3. can you check? please.
https://www.npmjs.com/package/react-native-metamap-sdk

**Comment by AvoSukiasyan** [comment]
@kdfemi  can you confirm? please.
