### ISSUE TITLE
TypeScript typing missing

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/metamap-reactnative-plugin#70]
Hello, when using the MetaMap SDK in TypeScript I get the following error:

```sh
Could not find a declaration file for module 'react-native-expo-metamap-sdk'. '/Users/code/project/node_modules/react-native-expo-metamap-sdk/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-expo-metamap-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-expo-metamap-sdk';`ts(7016)
```

Running `npm i --save-dev @types/react-native-expo-metamap-sdk` yields this error:
```sh
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-native-expo-metamap-sdk: Not found".
```

**Comment by AvoSukiasyan** [comment]
@bombillazo Hello. 
looks like you added  React Native Expo SDK but your project is React Native. can you remove Expo SDK and add React Native SDK? please. 
 https://www.npmjs.com/package/react-native-metamap-sdk

**Comment by AvoSukiasyan** [comment]
@bombillazo  can I have your package.json and package.lock files? please

**Comment by bombillazo** [comment]
I have various files (we use monorepos) and they are very large to be honest, what are you looking for ?

**Comment by AvoSukiasyan** [comment]
@bombillazo for my example project URL of the package.lock looks like this. what does your URL look like?
 "https://registry.npmjs.org/react-native-metamap-sdk/-/react-native-expo-metamap-sdk-4.5.1.tgz".

**Comment by bombillazo** [comment]
I cannot see the file, but I don't see any type definitions inside the metamap node module:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/44002321/197071672-cf707d31-b1d6-42d9-8232-7effa77ab604.png">

**Comment by LeoGCode** [comment]
This should be reopen the package are still missing the types definitions, the only thing required is add this code to the file a.ts
```typescript

declare module 'react-native-expo-metamap-sdk' {
  export const MetaMapRNSdk: {
    showFlow: (
      clientId: string,
      flowId: string | null,
      metadata: Record<string, string> | null,
    ) => void
    showFlowWithConfigurationId: (
      clientId: string,
      flowId: string | null,
      metadata: Record<string, string> | null,
      configurationId: string | null,
      encryptionConfigurationId: string | null,
    ) => void
  }
}
```
renamed to types.ts for more descriptive file and add the location to the types property in the package.json

**Comment by teampazi** [comment]
Hello @AvoSukiasyan  I am having this issue but there was no solution provided here for this issue please can you help.
I nam using expo 51, node 18, npm 9, typescript ~5.3.3, react 18.2.0 , react-native 0.74.1
