### ISSUE TITLE
Android 4.11.0 MetaMapRNSdkModule how did this build success?

### ISSUE THREAD

**Issue by liufengwei** [GetMetaMap/metamap-reactnative-plugin#74]
![screenshot-20230210-215318](https://user-images.githubusercontent.com/5564547/218112413-fcebb332-1773-441c-b9ec-90c8986fa8de.png)

**Comment by aposnovmati** [comment]
@liufengwei Hello, could you, please, clarify your request?

**Comment by liufengwei** [comment]
code in master/android/src/main/java/com/reactlibrary/MetaMapRNSdkModule.java line 68 build error,please check and correct!

**Comment by roy-moven** [comment]
I just ran in to the same problem. This Java doesn't even compile!

**Comment by roy-moven** [comment]
Ah I see it was fixed here: https://github.com/GetMetaMap/metamap-reactnative-plugin/commit/53d588522f124671a821ea27e9e1a17bc880d748

**Comment by roy-moven** [comment]
Bug was introduced here: https://github.com/GetMetaMap/metamap-reactnative-plugin/commit/dae1b89

**Comment by AvoSukiasyan** [comment]
@roy-moven the issue is fixed on the 4.11.3 version
