### ISSUE TITLE
buttonColor is not work for this page on ios (version 4.11.3 and 4.11.7)

### ISSUE THREAD

**Issue by liufengwei** [GetMetaMap/metamap-reactnative-plugin#75]
![image](https://github.com/GetMetaMap/metamap-reactnative-plugin/assets/5564547/806446da-d83c-4262-bbea-2902318b2a24)

**Comment by AvoSukiasyan** [comment]
Hi @liufengwei . Can you share implementation part? Please. I need it for reproduce the issue.

**Comment by AvoSukiasyan** [comment]
hi @liufengwei . I tried to reproduce the issue but couldn't. Can you share your company name? please I'll connect to support and they'll schedule a meeting.

**Comment by liufengwei** [comment]
you can send me email fengwei.liu@galactic.holdings

**Comment by AvoSukiasyan** [comment]
the problem is solved
