### ISSUE TITLE
page can not be close when select contry as Brazil on ios with version 4.11.7

### ISSUE THREAD

**Issue by liufengwei** [GetMetaMap/metamap-reactnative-plugin#76]
![img_v2_2371e014-5702-458d-9f1b-d1257dce278g](https://github.com/GetMetaMap/metamap-reactnative-plugin/assets/5564547/61a73d31-a240-4682-8dbb-0bdfe68c65d2)

**Comment by AvoSukiasyan** [comment]
hi @liufengwei . I'll fix it and get back to you

**Comment by AvoSukiasyan** [comment]
the problem is solved
