### ISSUE TITLE
nth-check 1.0.2 vulneravility

### ISSUE THREAD

**Issue by braian-wallbit** [GetMetaMap/metamap-reactnative-plugin#82]
Dependabot alert us about a vulnerability on this package. Here are the details:

> react-native-metamap-sdk@5.1.3 requires nth-check@^1.0.2 via a transitive dependency on css-select@2.1.0
> No patched version available for nth-check
> The earliest fixed version is 2.0.1.

**Vulnerability explanation** 

There is a Regular Expression Denial of Service (ReDoS) vulnerability in nth-check that causes a denial of service when parsing crafted invalid CSS nth-checks.

The ReDoS vulnerabilities of the regex are mainly due to the sub-pattern \s*(?:([+-]?)\s*(\d+))? with quantified overlapping adjacency.

Could you fix this dependency?
Thank you!

**Comment by AvoSukiasyan** [comment]
hi @braian-wallbit .
 I updated libraries and removed some library that is not necessary for our SDK . can you check it, please?
 https://www.npmjs.com/package/react-native-metamap-sdk/v/5.1.4

**Comment by braian-wallbit** [comment]
Thank you @AvoSukiasyan, we were able to update to 5.1.4 and the vulnerability was mark as remediated by the scanner!
