### ISSUE TITLE
Warnings from Native Module

### ISSUE THREAD

**Issue by LeoGCode** [GetMetaMap/metamap-reactnative-plugin#83]
I'm getting this warnings

WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

Following the implementation from [the docs](https://docs.metamap.com/docs/implementation-copy)

After searching the problem seen to be from the java file MetaMapRNSdkModule.java that are missing two methods 

```java
 // Required for rn built in EventEmitter Calls.
    @ReactMethod
    public void addListener(String eventName) {

    }

    @ReactMethod
    public void removeListeners(Integer count) {
```
Extracted from [stackoverflow](https://stackoverflow.com/questions/69538962/new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-requir)

I can make a PR to fix this if you want

**Comment by AvoSukiasyan** [comment]
hi @LeoGCode . 
thanks for notice. let me to check it and get back to you soon

**Comment by AvoSukiasyan** [comment]
hi @LeoGCode . sorry for delay i check and i same warming present for me too
can you open MR, please ? I'll. merge it
